title: EDM PORTFOLIO
logo: Assets/img/Pascubillo,%20Dexter G..png
description: Bachelor of Science in Information System Student of City College of Angeles
show_downloads: true
theme: jekyll-theme-architect
