title: EDM PORTFOLIO
logo: Assets/img/Pascubillo,%20Dexter G..png
description: Bachelor of Science in Information System Student of City College of Angeles
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0
